periph/devices

- nrzled/nrzled.go
Whether or not CS (chip select) is used really depends on the way how
you wire things together, not on the device you're talking to.
Not using CS (and explicitly telling the SPI controller about that)
might keep some pins free on pin-constrained boards, but also, some
controllers (or Linux drivers) don't support disabling CS, and fail when
that flag is given.
On the other hand, even though nrzleds don't make use of CS by
themselves, you could very well have some circuit in front to do the
chip select, and then actually write to different nrzled devices
sequentially.
Long-term, the fact on whether to do chip select should be specified
while passing in the SPI port to be used, as it really depends on the
way it's wired together on the specific board, not on the type of
device.
> nrzled: Don't set NoCS

- ep0099/doc.go
- ep0099/ep0099.go
- ep0099/ep0099_test.go
- ep0099/example_test.go
EP0099 is a stackable 4-channel relay hat that communicates with
platforms via i2c interface.
Manufacturer: 52pi
Wiki page: https://wiki.52pi.com/index.php/DockerPi_4_Channel_Relay_SKU:_EP-0099
> added support for EP0099

- mfrc522/commands/low_level.go
- mfrc522/mfrc522.go
Calling LowLevel.Init() in selectCard() clears the device interrupt
as a side effect, but another interrupt will occur due to the
subsquent operations. This additional host interrupt must be cleared
before the next call to selectCard.
https://github.com/google/periph/issues/425
> Prevent WaitForEdge() returning early after first call to selectCard()

- tlv493d/tlv493d.go
- tlv493d/tlv493d_test.go
Hello,
This is an addition to the TLV493D driver, in order to calibrate the "temperature offset". According to the [documentation](https://www.infineon.com/dgdl/Infineon-TLV493D-A1B6_3DMagnetic-UM-v01_03-EN.pdf?fileId=5546d46261d5e6820161e75721903ddd), section 3.2 "Calculation of the temperature", there is an Offset compensation, with a note: "The 340 as typical value may vary from device to device. Therefore for an accurate measurement the value at 25°C needs to be readout first and used as (correction) value instead of 340."
So this PR is basically the implementation of this.
Thanks!
Benjamin
> [TLV493D] Method to calibrate temperature offset

- inky/doc.go
- inky/inky.go
I have added auto opts detect and dev struct creationg with defaults from the detected opts as mentioned in #11.
While I was at it I also added support for pHAT v2 which is simply a pHAT with a [small resolution difference](https://github.com/pimoroni/inky/blob/85f97ffa9ae775d4de71d5179af792ccb7080ee0/library/inky/phat.py#L15).
> [Inky] autodetect board opts and pHAT v2 support

- ssd1306/ssd1306.go
- ssd1306/ssd1306_test.go
This is useful for controlled, smooth, vertical scrolling (to new content, not a looping scroll like `Dev.Scroll`. This is 10.1.6 from page 36 of [the datasheet].
With double-buffering, a 128x32 ssd1306 can scroll indefinitely. This can be done by setting `Opts.H: 64` (which does unfortunately dim the display a little bit), and using the lower 32 lines (which are off-screen) as a second image buffer.
[the datasheet]: https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf
> ssd1306: Add SetDisplayStartLine

- ds18b20/doc.go
- ds18b20/ds18b20.go
This is a followup of #18.
This ensures the right conversion time is used and the resolution setting is skipped for the DS18S20. (I totally missed that in #18)
Also addresses the remarks of #18 regarding the doc.go.
> ds18b20: fixed conversion time for DS18S20 + cleanup

- mfrc522/mfrc522.go
4-byte UIDs incorrectly included a 5th csum byte. 7-byte UIDs were unaffected.
fixes #21
> mfrc522 - Fix 4-byte tag UIDs

- mfrc522/mfrc522.go
Related to #21 I screwed up when we changed the default behaviour from bogus to not-bogus and overlooked the default value, it must be false because there is only an option to set it to true.
> mfrc522: The default should be not bogus

- waveshare2in13v2/example_test.go
- waveshare2in13v2/waveshare213v2.go
Translate magic numbers to named constants based on datasheet and add missing calls to `dev.Init` in example code.
> waveshare2in13v2: Add constants, add missing init to example

- go.mod
- go.sum
- waveshare2in13v2/example_test.go
The waveshare2in13v2 example was evidently copied from the epd example,
but didn't comment out the code pulling in additional dependencies.
> waveshare2in13v2: Remove dependencies on fogleman/gg and golang/freetype

- .github/workflows/test.yml
- go.mod
Go 1.13 was released in September 2019, more than two years ago.
Updating to one later release should be fine.
The primary reason for doing this is the introduction of
"testing".T.Cleanup in Go 1.14 (https://pkg.go.dev/testing#T.Cleanup).
> Bump Go version in go.mod and for quick tests to 1.14

- videosink/display.go
- videosink/display_test.go
- videosink/encoder.go
- videosink/format.go
- videosink/format_test.go
- videosink/handler.go
- videosink/handler_test.go
- videosink/writer.go
- videosink/writer_test.go
The videosink package provides a display driver implementing an HTTP
request handler. Client requests get an initial snapshot of the graphics
buffer and are updated further on every change.
Provides the basic implementation for #26. Still to be done are example code and `periph/cmd` integration.
> Add videosink display driver

- videosink/display.go
- videosink/encoder.go
- videosink/handler.go
Expose the quality settings for the JPEG encoder and the compression
level of the PNG encoder via the Options structure.
Relates to #26.
> videosink: Add options for JPEG and PNG encoders

- waveshare2in13v2/waveshare213v2.go
- waveshare2in13v2/waveshare213v2_test.go
Dev.Clear: Avoid writing one beyond the end of the line. Also build the
row data only once before sending it for each line.
Dev.Draw, Dev.DrawPartial: Deduplicate logic for iterating over pixels
and simplify it such that a whole row of bits is built before sending
them in one go.
Tested using a Waveshare e-Paper 2.13in V2 display.
> waveshare2in13v2: Deduplicate and simplify logic for sending data

- waveshare2in13v2/doc.go
- waveshare2in13v2/drawing.go
- waveshare2in13v2/drawing_test.go
- waveshare2in13v2/waveshare213v2.go
This is an API-breaking change, albeit a simple one: Previously the `Dev.Clear` function received a byte named "color". It was sent directly to the display, thus acting more like a pattern to fill the display with. In practice only 0 and 255 are likely to be used (equivalent to `image1bit.Off` and `image1bit.On` respectively). To match the `Dev.Draw` interface a generic `color.Color` is now used.
> waveshare213v2: Add tests for clearing, use better color type

- waveshare2in13v2/errorhandler.go
- waveshare2in13v2/waveshare213v2.go
The busy pin from the e-paper display is only used to read, not to
write, and thus there's no need for the PinIO interface. PinIn is
enough.
In addition the WaitForEdge function can be used to shorten the delays
when waiting for the display to become idle. Spurious or missed edges
are acceptable: the delay isn't very long.
> waveshare213v2: Make busy a PinIn, use WaitForEdge

- waveshare2in13v2/controller.go
- waveshare2in13v2/controller_test.go
- waveshare2in13v2/drawing.go
- waveshare2in13v2/drawing_test.go
- waveshare2in13v2/example_test.go
- waveshare2in13v2/waveshare213v2.go
This series of changes implements partial, flicker-free update for Waveshare 2.13in v2 displays. Sleep modes and better power management will follow later.
> waveshare213v2: Implement partial updates

- waveshare2in13v2/doc.go
Additional research provided information confirming that Waveshare
2.13in v2 displays are in fact GDEH0213B72, not GDEH0213B73, or at least
equivalent.
> waveshare2in13v2: Clarify documentation on controller

- ssd1306/image1bit/image1bit.go
- waveshare2in13v2/drawing.go
- waveshare2in13v2/waveshare213v2.go
- waveshare2in13v2/waveshare213v2_test.go
* Add tests for `waveshare2in13v2.New()`
* Swap the order of width and height in `waveshare2in13v2.Dev.String()`
* Simplify memory configuration
> Minor fixes for waveshare2in13v2, fix typos in image1bit

- waveshare2in13v2/drawing.go
- waveshare2in13v2/drawing_test.go
- waveshare2in13v2/waveshare213v2.go
- waveshare2in13v2/waveshare213v2_test.go
A new option named `Origin` controls which of the four corners of the display should be used as the (0,0) position for the image. The included unittests may seem excessive, but they are the result of many off-by-one errors and other mistakes I made while developing this series.
> waveshare2in13v2: Support rotation of image

- CONTRIBUTORS
- tca95xx/example_test.go
- tca95xx/pins.go
- tca95xx/registers.go
- tca95xx/tca9535_test.go
- tca95xx/tca95xx.go
- tca95xx/variants.go
1. :thumbsup:
2. n/a
3. :thumbsup:
- I am able to test the TCA9534 and TCA9535 chips using a RPI4.  I included chips that were nearly identical as to reduce the likelihood of introducing a bug.
- I added a conn.Conn interface and implemented that for the extender to allow access to the entire port as a byte.
- This code is based on the `mcp23xxx` code pretty heavily.
> Add support for tca95xx i/o extenders.

- tlv493d/tlv493d.go
When an error occurs, it is necessary to reset the sensor as per the documentation. This will send a recovery command followed by the standard start procedure.
> tlv493d: Auto-reset TLV493D on error

- ina219/ina219.go
The current and shunt voltage register values are signed, twos complement format. In my tests interpreting them directly in the way implemented here gave output consistent with other ina219 libraries.
> ina219: Interpret signed output register values

- lirc/lirc.go
1. Please prefix the issue title with the primary package affected. For example,
Fixes periph.io/x/devices/v3/devices/lirc/lirc.go:67
2. Mention the issue number it fixes or add the details of the changes if it
doesn't have a specific issue. Examples:
- Fixes #56
P.S. There's already another issue when the command is sent successfully but the parse of lirc.go cannot recognize it the the SEND_ONCE trigger a raw config. I will fill another issue once I have the solution.
> lirc requries linebreak \n for SEND_ONCE

- CONTRIBUTORS
- adxl345/adxl345.go
- adxl345/doc.go
- adxl345/example/example.go
1. Please prefix the issue title with the primary package affected. For example,
if this PR fixes periph.io/x/devices/v3/cap1xxx, prefix the PR title with "cap1xxx:".
2. Mention the issue number it fixes or add the details of the changes if it
doesn't have a specific issue. Examples:
- Added basic support for the adxl345 accelerometer.
3. Once integrated, send a PR to https://github.com/periph/cmd to leverage the
new functionality (if relevant).
> adxl345: Driver, initial commit for review.

- aht20/aht20.go
- aht20/error.go
Implemented the AHT20 environmental sensor using the `SenseEnv` interface. Implementation is based on this [Datasheet](https://files.seeedstudio.com/wiki/Grove-AHT20_I2C_Industrial_Grade_Temperature_and_Humidity_Sensor/AHT20-datasheet-2020-4-16.pdf). Tested on a RaspberryPi with the AHT20 sensor.
**Features:**
- Pure Go, no dependencies
- `Sense()` reads a single measurement
- `SenseContinuous()` reads measurements with the given interval into a channel (or as fast as possible if it is too small)
- `Halt()` stops a continuous measurement
- Options:
- A configurable polling interval if the measurement is not finished after 80ms. Defaults to 10ms
- A configurable measurement read timeout after the initial delay of 80ms. Default is 150ms.
- Optionally CRC8 data validation of measurements. …
> Add AHT20 sensor

- aht20/aht20.go
- aht20/aht20_test.go
- Add tests for all exported methods of the AHT20 device (except `SenseContinuous()`)
- Fix `IsInitialized()` always returning `false` due to data byte not being set
> Add AHT20 tests

- aht20/doc.go
Add `doc.go` for package `aht20` which I forgot in my last PR
> Add doc file for AHT20

- bmxx80/bmx280.go
- bmxx80/bmx280_test.go
- bmxx80/bmxx80.go
- bmxx80/doc.go
I cannot use the `SenseContinuous` option with my hardware as there are additional bus contention issues to deal with, but would like to use the built in filtering on the BME sensors. 
In order to prevent current implementations from changing their behavior I added a new initialization option to set the standby time. When the `Filter` and `Standby` options are set in the device options the sensor will initialize to the `normal` mode instead of `sleep`. Additionally when calling `Sense` mode will not be set to `forced` if the `Filter` and `Standby` options are set as this would prevent the continuous sampling needing for the filtration.
> periph.io/x/devices/v3/bmxx80: add support for filters without using SenseContinuous

- tic/doc.go
- tic/example_test.go
- tic/registers.go
- tic/registers_test.go
- tic/tic.go
- tic/tic_test.go
This PR adds functionality for interfacing with [Pololu Tic Stepper Motor Controllers](https://www.pololu.com/category/212/tic-stepper-motor-controllers) over I²C.
The `tic` package is based on [github.com/pololu/tic-arduino](https://github.com/pololu/tic-arduino), with adoption of Go-style error handling, [periph/conn](https://pkg.go.dev/periph.io/x/periph/conn), and other usability improvements.
> tic: Add I²C support for Tic Stepper Motor Controllers

- scd4x/README.md
- scd4x/doc.go
- scd4x/example_test.go
- scd4x/scd4x.go
- scd4x/scd4x_test.go
@maruel I'm mostly liking they way I did the unit tests. I get live device, and playback testing without lots of extra code.
What are your thoughts? Do you have any ideas on making it more elegant?
> scd4x: SCD4x CO2 Sensor - Initial Add

- ep0099/ep0099.go
- ep0099/ep0099_test.go
Add new structure (Opts) and 2 new methods (NewWithOpts, ReadStates) to provide the ability to load the state from the device instead of simply resetting the device on start.
Promoted Reset() to be a public function so it can be called to reset the state if required.
> ep0099: optionally read device state on new

- ina219/ina219.go
Fixes #73
I would have wrapped the errors returned since I know that's what you prefer, but the tests would have been pretty broken and I didn't see a straight-forward repair.
> ina219: restructure so voltage can be returned even if power/current invalid

- go.mod
- go.sum
- serlcd/example_test.go
- serlcd/serlcd.go
- serlcd/serlcd_test.go
Bumps conn to 3.7.2 to get the new text interface, and the GPIO group interface.
> Add Support for SparkFun SerLCD Display

- inky/types.go
Run the `stringer` command (for code generation) using `go run` instead of `go install` to avoid affecting the developer's global `$GOBIN`.
> inky: run stringer with "go run"

- inky/doc.go
- inky/impression.go
- inky/types.go
- inky/types_string.go
Inky Impression 7.3" is a larger e-ink display that unlike smaller variants is based on AC073TC1A rather than UC8159.
This PR is effectively a port of pimoroni/inky#158 since the difference is primarily in the reset and update commads.
(draft until I have a chance to properly test)
> [inky] Add Inky Impression 7.3" support

- nxp74hc595/74hc595.go
- nxp74hc595/74hc595_test.go
- nxp74hc595/example_test.go
- nxp74hc595/pin.go
The 74HC595 converts a serial data stream to parallel output on it's data pins. The Adafruit I2C/SPI backpack uses this device for the SPI side of the backpack.
I'll be adding an SPI backpack to the HD44780 LCD display that uses this.
> Add Support for 74HC595 Serial -> Parallel Shift Register

- inky/impression.go
Fix typo in initialization of bounds when bounds are not explicitely set by the user.
This issue has been reported by @kedare in https://github.com/periph/devices/pull/75#issuecomment-2692847224
Cc: @fstanis @gsexton
> inky/impression: fix init of bounds

- inky/impression.go
Minor refactor to embed `Dev` directly into `DevImpression` instead of via a pointer.
Cc: @fstanis @gsexton
> inky/impression: embed Dev

- go.mod
- go.sum
- inky/impression.go
- inky/inky.go
- inky/types.go
Fixes #105
This PR fixes issues in the Inky 7.3 Impression Driver.
* Changed the SPI CS pin to work under automatic or manual control. This allows it to work when CS is controlled by SPI, or when it is controlled manually. We don't want it to fail in the configuration the Pimoroni python driver requires.
* Changed the wait() routine to use a 10ms debounce on WaitForEdge() as the python driver does. 
* Fixed an issue in the image copy where the image byte wasn't copied (see line 530 of impression.go).
* If the BUSY line is high on entry to wait to go directly to a timed wait as the python driver does.
* Fixed errors in the palette definitions. Removed extra memory allocation.
> inky: Fix Impression Driver

- inky/opts.go
This PR adds support for the Inky Impression 7.3 7-color model. The only relevant change is mapping the PCB variant to the device model when trying to detect the device's opts.
> Support Inky Impression 7.3 7-color

- inky/impression.go
- inky/opts.go
- inky/types.go
- inky/types_string.go
- Ported the [Python driver for the 2025 version of the Inky Impression 7.3 based on eInk Spectra 6](https://github.com/pimoroni/inky/blob/fef67aab73bb2b6def1eca6003a3f5a3ccec0741/inky/inky_e673.py)
- Updated the Inky options to auto-detect the Spectra6 version of the display
I only have the 7.3-inch version to test, so this PR omits adding support for the 13 inch version of the display, but I imagine that would not be complicated to support.
> inky: Add Impression 7.3 Spectra6 support
